import { type JSX } from 'react'
import type { IconType } from 'react-icons'
import {
  // Type-emblem fallbacks
  GiDeathSkull,
  GiDragonHead,
  GiPawPrint,
  GiDevilMask,
  GiVisoredHelm,
  GiGiant,
  GiEyeball,
  GiGears,
  GiFlame,
  GiFairy,
  GiThreeLeaves,
  GiSlime,
  GiSnake,
  GiAngelWings,
  GiCheckedShield,
  // Class emblems (icons already in monster-emblem block above are not redeclared)
  GiLyre,
  GiCrossShield,
  GiEyeOfHorus,
  // Race emblems
  GiElfHelmet,
  GiElfEar,
  GiSpiderAlt,
  GiPointyHat,
  GiDwarfFace,
  GiMiningHelmet,
  GiSlingshot,
  GiImp,
  GiLizardman,
  GiSnakeTongue,
  GiCat,
  GiOakLeaf,
  GiRaven,
  GiSeagull,
  GiTrident,
  GiTurtle,
  GiRobotGolem,
  GiWolfHead,
  GiDominoMask,
  GiCardJoker,
  GiGoat,
  GiCentaur,
  GiGoblinHead,
  GiSpartanHelmet,
  GiBearFace,
  GiOrcHead,
  GiClaws,
  GiAlienStare,
  GiMeditation,
  GiSharkJaws,
  GiFishMonster,
  GiBrainTentacle,
  // Per-monster emblems
  GiCultist,
  GiHolySymbol,
  GiMonkFace,
  GiKnightBanner,
  GiBarbarian,
  GiBowman,
  GiBoxingGlove,
  GiSpy,
  GiTopHat,
  GiFarmer,
  GiBandit,
  GiPirateCaptain,
  GiCenturionHelmet,
  GiCrossedSwords,
  GiSwordsEmblem,
  GiWizardFace,
  GiBattleGear,
  GiBlackKnightHelm,
  GiArmorVest,
  GiBeard,
  GiBattleAxe,
  GiLizardTongue,
  GiRat,
  GiWerewolf,
  GiWolfHowl,
  GiBearHead,
  GiPolarBear,
  GiBat,
  GiOwl,
  GiHawkEmblem,
  GiEagleHead,
  GiVulture,
  GiFrog,
  GiSnakeBite,
  GiToadTeeth,
  GiLion,
  GiTiger,
  GiSkullSabertooth,
  GiBoar,
  GiBoarTusks,
  GiHorseHead,
  GiCrocJaws,
  GiSpiderFace,
  GiScorpion,
  GiDinosaurRex,
  GiSpikedShell,
  GiTriceratopsHead,
  GiTRexSkull,
  GiCyclops,
  GiBee,
  GiPiranha,
  GiSkeleton,
  GiPirateGrave,
  GiBoneGnawer,
  GiFangedSkull,
  GiMummyHead,
  GiHaunting,
  GiGhost,
  GiFloatingGhost,
  GiVampireCape,
  GiVampireDracula,
  GiShadowFollower,
  GiCarnivoreMouth,
  GiOgre,
  GiTroll,
  GiDualityMask,
  GiStoneTower,
  GiStoneSphere,
  GiIciclesAura,
  GiFireSilhouette,
  GiWyvern,
  GiDragonSpiral,
  GiDragonBreath,
  GiHarpy,
  GiGriffinSymbol,
  GiAlienBug,
  GiSnakeSpiral,
  GiSpikedDragonHead,
  GiGargoyle,
  GiMonsterGrasp,
  GiPegasus,
  GiUnicorn,
  GiMinotaur,
  GiMedusaHead,
  GiHydra,
  GiFangs,
  GiHoodedAssassin,
  GiFireRing,
  GiTornado,
  GiWaterSplash,
  GiCrystalShine,
  GiTentacleStrike,
  GiVomiting,
  GiBleedingEye,
  GiAllSeeingEye,
  GiSwordSpin,
  GiCloak,
  GiClayBrick,
  GiGolemHead,
  GiAnvil,
  GiIceCube,
  GiAcidBlob,
  GiAcid,
  GiTreeBranch,
  GiVineLeaf,
  GiPlantsAndAnimals,
  GiTreeFace,
  GiCarnivorousPlant,
  GiFairyWand,
  GiFlowers,
  GiAngelOutfit,
  GiFireGem,
  GiAxolotl,
  GiWingedSword,
  GiSpikedShoulderArmor,
  GiCrownedSkull,
  GiSarcophagus,
  GiSkullBolt,
  GiDelicatePerfume,
  GiHornedHelm,
  GiHornedSkull,
  GiFleshyMass,
  GiPincers,
  GiTripleScratches,
  GiPounce,
  GiBeetleShell,
  GiWormMouth,
  GiCaterpillar,
  GiCentipede,
  GiBowArrow,
  GiCauldron,
  GiDreamCatcher,
  GiSittingDog,
  GiCloakDagger,
  GiGladius,
  GiWizardStaff,
  GiHoodedFigure,
  GiCloudRing,
  GiLightningStorm,
  GiDragonShield,
  GiDragonOrb,
  GiDoubleDragon,
  GiVolcano,
  GiBubbles,
  GiSplash,
  GiSnowflake1,
  GiSmokeBomb,
  GiHound,
  GiJellyfish,
  GiTribalMask,
  GiHarp,
  GiSwordwoman,
  GiHealing,
  GiSunbeams,
  GiWarPick,
  GiTrophy,
  GiSwordSlice,
  GiFireSpellCast,
  GiOpenPalm,
  GiNinjaMask,
  GiYinYang,
  GiHolyGrail,
  GiTrefoilLily,
  GiSwordWound,
  GiArcheryTarget,
  GiPawHeart,
  GiTreasureMap,
  GiBackstab,
  GiMagicPalm,
  GiDragonBalls,
  GiSpiralBloom,
  GiBatWing,
  GiSquidHead,
  GiFireball,
  GiMagicShield,
  GiSkullStaff,
  GiMagicGate,
  GiThunderStruck,
  GiClover,
  GiOpenBook,
  GiDramaMasks,
  GiPotionBall,
  GiSentryGun,
  GiAnvilImpact,
  GiRobotHelmet,
  GiTreeRoots,
  GiMoonClaws,
  GiAstrolabe,
  GiIceberg,
  GiSeaDragon,
  GiOctopus,
  GiSunPriest,
  GiSeaSerpent,
  GiCobra,
  GiFrogPrince,
  GiEagleEmblem,
  GiSalamander,
  GiDjinn,
  GiTigerHead,
  GiFrostfire,
  GiSeaTurtle,
  GiCrestedHelmet
} from 'react-icons/gi'

// Each monster type / playable race maps to its own game-icons.net emblem.
const TYPE_EMBLEM: Record<string, IconType> = {
  нежить: GiDeathSkull,
  дракон: GiDragonHead,
  зверь: GiPawPrint,
  исчадие: GiDevilMask,
  гуманоид: GiVisoredHelm,
  великан: GiGiant,
  аберрация: GiEyeball,
  конструкт: GiGears,
  элементаль: GiFlame,
  фея: GiFairy,
  растение: GiThreeLeaves,
  слизь: GiSlime,
  чудовище: GiSnake,
  небожитель: GiAngelWings,
  рой: GiPawPrint
}

// Per-monster overrides keyed by lower-cased Russian name. Whenever the
// monstrosity / humanoid / construct fallback would be too generic (a snake
// for an owlbear, a helmet for a werewolf), we pin a hand-picked emblem.
const NAME_EMBLEM: Record<string, IconType> = {
  // — Гуманоиды —
  'гоблин': GiGoblinHead,
  'босс гоблинов': GiSwordsEmblem,
  'хобгоблин': GiSpartanHelmet,
  'капитан хобгоблинов': GiCenturionHelmet,
  'багбир': GiBearFace,
  'орк': GiOrcHead,
  'вождь орков': GiBattleGear,
  'гнолл': GiCarnivoreMouth,
  'вожак гноллов': GiClaws,
  'кобольд': GiLizardTongue,
  'дроу': GiHoodedAssassin,
  'бандит': GiBandit,
  'главарь разбойников': GiPirateCaptain,
  'стражник': GiVisoredHelm,
  'культист': GiCultist,
  'послушник': GiMonkFace,
  'жрец': GiHolySymbol,
  'рыцарь': GiKnightBanner,
  'маг': GiWizardFace,
  'берсерк': GiBarbarian,
  'ветеран': GiCrossedSwords,
  'разведчик': GiBowman,
  'громила': GiBoxingGlove,
  'шпион': GiSpy,
  'друид': GiOakLeaf,
  'дворянин': GiTopHat,
  'мирный житель': GiFarmer,
  'людоящер': GiLizardman,
  'троглодит': GiSnakeTongue,
  'веркрыса': GiRat,
  'вервольф': GiWerewolf,

  // — Нежить —
  'скелет': GiSkeleton,
  'зомби': GiPirateGrave,
  'гуль': GiBoneGnawer,
  'вурдалак': GiFangedSkull,
  'мумия': GiMummyHead,
  'тень': GiShadowFollower,
  'умертвие': GiBlackKnightHelm,
  'призрак': GiGhost,
  'спектр': GiFloatingGhost,
  'баньши': GiHaunting,
  'порождение вампира': GiVampireCape,
  'вампир': GiVampireDracula,

  // — Звери —
  'крыса': GiRat,
  'гигантская крыса': GiRat,
  'рой крыс': GiRat,
  'летучая мышь': GiBat,
  'кот': GiCat,
  'ворон': GiRaven,
  'орёл': GiEagleHead,
  'ястреб': GiHawkEmblem,
  'лягушка': GiFrog,
  'ядовитая змея': GiSnakeBite,
  'гигантская жаба': GiToadTeeth,
  'стирга': GiBat,
  'волк': GiWolfHead,
  'жуткий волк': GiWolfHowl,
  'бурый медведь': GiBearHead,
  'чёрный медведь': GiPawPrint,
  'полярный медведь': GiPolarBear,
  'кабан': GiBoar,
  'гигантский кабан': GiBoarTusks,
  'лев': GiLion,
  'тигр': GiTiger,
  'саблезубый тигр': GiSkullSabertooth,
  'пантера': GiPawPrint,
  'боевой конь': GiHorseHead,
  'крокодил': GiCrocJaws,
  'гигантский паук': GiSpiderAlt,
  'гигантский волчий паук': GiSpiderFace,
  'гигантский скорпион': GiScorpion,
  'аллозавр': GiDinosaurRex,
  'анкилозавр': GiSpikedShell,
  'трицератопс': GiTriceratopsHead,
  'тираннозавр': GiTRexSkull,
  'рой насекомых': GiBee,
  'рой квипперов': GiPiranha,

  // — Великаны —
  'огр': GiOgre,
  'тролль': GiTroll,
  'эттин': GiDualityMask,
  'холмовой великан': GiGiant,
  'каменный великан': GiStoneTower,
  'ледяной великан': GiIciclesAura,
  'огненный великан': GiBattleAxe,

  // — Драконы —
  'виверна': GiWyvern,
  'молодой красный дракон': GiDragonHead,
  'вирмлинг чёрного дракона': GiDragonHead,
  'вирмлинг красного дракона': GiDragonHead,
  'вирмлинг синего дракона': GiDragonHead,
  'вирмлинг зелёного дракона': GiDragonHead,
  'вирмлинг белого дракона': GiDragonHead,
  'взрослый чёрный дракон': GiDragonSpiral,
  'взрослый красный дракон': GiDragonBreath,

  // — Чудовища —
  'совомедведь': GiOwl,
  'гарпия': GiHarpy,
  'гиппогриф': GiSeagull,
  'грифон': GiGriffinSymbol,
  'анкег': GiAlienBug,
  'василиск': GiSnakeSpiral,
  'мантикора': GiSpikedDragonHead,
  'кокатрикс': GiFangs,
  'мимик': GiMonsterGrasp,
  'пегас': GiPegasus,
  'единорог': GiUnicorn,
  'минотавр': GiMinotaur,
  'медуза': GiMedusaHead,
  'гидра': GiHydra,
  'тарраск': GiCyclops,
  'доппельгангер': GiCardJoker,
  'горгулья': GiGargoyle,

  // — Элементали —
  'огненный элементаль': GiFireRing,
  'воздушный элементаль': GiTornado,
  'земляной элементаль': GiStoneSphere,
  'водяной элементаль': GiWaterSplash,
  'ксорн': GiCrystalShine,

  // — Аберрации —
  'аболет': GiTentacleStrike,
  'бормочущий ротовик': GiVomiting,
  'нотик': GiBleedingEye,
  'свежеватель разума': GiBrainTentacle,
  'бехолдер': GiAllSeeingEye,

  // — Исчадия —
  'имп': GiImp,
  'квазит': GiDominoMask,
  'дретч': GiDevilMask,
  'врок': GiVulture,
  'балор': GiFireSilhouette,
  'бородатый дьявол': GiBeard,

  // — Конструкты —
  'оживший доспех': GiArmorVest,
  'летающий меч': GiSwordSpin,
  'пугало': GiCloak,
  'глиняный голем': GiClayBrick,
  'каменный голем': GiGolemHead,
  'железный голем': GiAnvil,

  // — Слизи —
  'желатиновый куб': GiIceCube,
  'серая слизь': GiAcidBlob,
  'чёрная слизь': GiAcid,

  // — Растения —
  'ветвистая зараза': GiTreeBranch,
  'вьющаяся зараза': GiVineLeaf,
  'блуждающий куст': GiCarnivorousPlant,
  'бродячая куча': GiPlantsAndAnimals,
  'древень': GiTreeFace,

  // — Феи —
  'пикси': GiFairyWand,
  'дриада': GiFlowers,
  'сатир': GiGoat,

  // — Небожители —
  'дэва': GiAngelOutfit,
  'планетар': GiAngelWings,
  'архонт-светоч': GiFireGem,

  // — Доп. исчадия —
  'хезроу': GiAxolotl,
  'эриния': GiWingedSword,
  'шипастый дьявол': GiSpikedShoulderArmor,

  // — Нежить-боссы —
  'лич': GiCrownedSkull,
  'лорд-мумия': GiSarcophagus,
  'пылающий череп': GiSkullBolt,

  // — Исчадия (топ) —
  'суккуб': GiDelicatePerfume,
  'камбион': GiHornedHelm,
  'костяной дьявол': GiHornedSkull,
  'лемур': GiFleshyMass,
  'рогатый дьявол': GiTrident,
  'глабрезу': GiPincers,

  // — Чудовища-классика —
  'химера': GiTripleScratches,
  'ускользающий зверь': GiPounce,
  'ржавник': GiBeetleShell,
  'лиловый червь': GiWormMouth,
  'ремораз': GiCaterpillar,
  'бехир': GiCentipede,

  // — Феи и карги —
  'спрайт': GiBowArrow,
  'зелёная карга': GiCauldron,
  'ночная карга': GiDreamCatcher,
  'мерцающий пёс': GiSittingDog,

  // — NPC —
  'наёмный убийца': GiCloakDagger,
  'гладиатор': GiGladius,
  'архимаг': GiWizardStaff,
  'фанатик культа': GiHoodedFigure,

  // — Великаны (топ) —
  'облачный великан': GiCloudRing,
  'штормовой великан': GiLightningStorm,

  // — Драконы (доп.) —
  'взрослый белый дракон': GiDragonShield,
  'взрослый зелёный дракон': GiDragonOrb,
  'взрослый синий дракон': GiDoubleDragon,
  'древний красный дракон': GiVolcano,

  // — Мелочёвка —
  'паровой мефит': GiBubbles,
  'грязевой мефит': GiSplash,
  'ледяной мефит': GiSnowflake1,
  'дымовой мефит': GiSmokeBomb,
  'адская гончая': GiHound,
  'ворг': GiWolfHead,
  'золотистый студень': GiJellyfish,

  // — Классы как противники: Варвар —
  'варвар-берсерк (3 ур.)': GiBarbarian,
  'варвар-берсерк (7 ур.)': GiBarbarian,
  'варвар-берсерк (13 ур.)': GiBarbarian,
  'варвар-берсерк (18 ур.)': GiBarbarian,
  'варвар — тотемный воин (3 ур.)': GiTribalMask,
  'варвар — тотемный воин (7 ур.)': GiTribalMask,
  'варвар — тотемный воин (13 ур.)': GiTribalMask,
  'варвар — тотемный воин (18 ур.)': GiTribalMask,

  // — Классы как противники: Бард —
  'бард коллегии знаний (3 ур.)': GiHarp,
  'бард коллегии знаний (7 ур.)': GiHarp,
  'бард коллегии знаний (13 ур.)': GiHarp,
  'бард коллегии знаний (18 ур.)': GiHarp,
  'бард коллегии доблести (3 ур.)': GiSwordwoman,
  'бард коллегии доблести (7 ур.)': GiSwordwoman,
  'бард коллегии доблести (13 ур.)': GiSwordwoman,
  'бард коллегии доблести (18 ур.)': GiSwordwoman,

  // — Классы как противники: Жрец —
  'жрец домена жизни (3 ур.)': GiHealing,
  'жрец домена жизни (7 ур.)': GiHealing,
  'жрец домена жизни (13 ур.)': GiHealing,
  'жрец домена жизни (18 ур.)': GiHealing,
  'жрец домена света (3 ур.)': GiSunbeams,
  'жрец домена света (7 ур.)': GiSunbeams,
  'жрец домена света (13 ур.)': GiSunbeams,
  'жрец домена света (18 ур.)': GiSunbeams,
  'жрец домена войны (3 ур.)': GiWarPick,
  'жрец домена войны (7 ур.)': GiWarPick,
  'жрец домена войны (13 ур.)': GiWarPick,
  'жрец домена войны (18 ур.)': GiWarPick,
  'жрец домена бури (3 ур.)': GiThunderStruck,
  'жрец домена бури (7 ур.)': GiThunderStruck,
  'жрец домена бури (13 ур.)': GiThunderStruck,
  'жрец домена бури (18 ур.)': GiThunderStruck,
  'жрец домена природы (3 ур.)': GiClover,
  'жрец домена природы (7 ур.)': GiClover,
  'жрец домена природы (13 ур.)': GiClover,
  'жрец домена природы (18 ур.)': GiClover,
  'жрец домена знания (3 ур.)': GiOpenBook,
  'жрец домена знания (7 ур.)': GiOpenBook,
  'жрец домена знания (13 ур.)': GiOpenBook,
  'жрец домена знания (18 ур.)': GiOpenBook,
  'жрец домена обмана (3 ур.)': GiDramaMasks,
  'жрец домена обмана (7 ур.)': GiDramaMasks,
  'жрец домена обмана (13 ур.)': GiDramaMasks,
  'жрец домена обмана (18 ур.)': GiDramaMasks,

  // — Классы как противники: Артефактор —
  'артефактор-алхимик (3 ур.)': GiPotionBall,
  'артефактор-алхимик (7 ур.)': GiPotionBall,
  'артефактор-алхимик (13 ур.)': GiPotionBall,
  'артефактор-алхимик (18 ур.)': GiPotionBall,
  'артефактор-артиллерист (3 ур.)': GiSentryGun,
  'артефактор-артиллерист (7 ур.)': GiSentryGun,
  'артефактор-артиллерист (13 ур.)': GiSentryGun,
  'артефактор-артиллерист (18 ур.)': GiSentryGun,
  'артефактор — боевой кузнец (3 ур.)': GiAnvilImpact,
  'артефактор — боевой кузнец (7 ур.)': GiAnvilImpact,
  'артефактор — боевой кузнец (13 ур.)': GiAnvilImpact,
  'артефактор — боевой кузнец (18 ур.)': GiAnvilImpact,
  'артефактор-бронник (3 ур.)': GiRobotHelmet,
  'артефактор-бронник (7 ур.)': GiRobotHelmet,
  'артефактор-бронник (13 ур.)': GiRobotHelmet,
  'артефактор-бронник (18 ур.)': GiRobotHelmet,

  // — Классы как противники: Друид —
  'друид круга земли (3 ур.)': GiTreeRoots,
  'друид круга земли (7 ур.)': GiTreeRoots,
  'друид круга земли (13 ур.)': GiTreeRoots,
  'друид круга земли (18 ур.)': GiTreeRoots,
  'друид круга луны (3 ур.)': GiMoonClaws,
  'друид круга луны (7 ур.)': GiMoonClaws,
  'друид круга луны (13 ур.)': GiMoonClaws,
  'друид круга луны (18 ур.)': GiMoonClaws,
  'друид круга звёзд (3 ур.)': GiAstrolabe,
  'друид круга звёзд (7 ур.)': GiAstrolabe,
  'друид круга звёзд (13 ур.)': GiAstrolabe,
  'друид круга звёзд (18 ур.)': GiAstrolabe,

  // — Классы как противники: Воин —
  'воин-чемпион (3 ур.)': GiTrophy,
  'воин-чемпион (7 ур.)': GiTrophy,
  'воин-чемпион (13 ур.)': GiTrophy,
  'воин-чемпион (18 ур.)': GiTrophy,
  'воин — мастер боевых искусств (3 ур.)': GiSwordSlice,
  'воин — мастер боевых искусств (7 ур.)': GiSwordSlice,
  'воин — мастер боевых искусств (13 ур.)': GiSwordSlice,
  'воин — мастер боевых искусств (18 ур.)': GiSwordSlice,
  'воин — мистический рыцарь (3 ур.)': GiFireSpellCast,
  'воин — мистический рыцарь (7 ур.)': GiFireSpellCast,
  'воин — мистический рыцарь (13 ур.)': GiFireSpellCast,
  'воин — мистический рыцарь (18 ур.)': GiFireSpellCast,

  // — Классы как противники: Монах —
  'монах открытой ладони (3 ур.)': GiOpenPalm,
  'монах открытой ладони (7 ур.)': GiOpenPalm,
  'монах открытой ладони (13 ур.)': GiOpenPalm,
  'монах открытой ладони (18 ур.)': GiOpenPalm,
  'монах пути тени (3 ур.)': GiNinjaMask,
  'монах пути тени (7 ур.)': GiNinjaMask,
  'монах пути тени (13 ур.)': GiNinjaMask,
  'монах пути тени (18 ур.)': GiNinjaMask,
  'монах четырёх стихий (3 ур.)': GiYinYang,
  'монах четырёх стихий (7 ур.)': GiYinYang,
  'монах четырёх стихий (13 ур.)': GiYinYang,
  'монах четырёх стихий (18 ур.)': GiYinYang,

  // — Классы как противники: Паладин —
  'паладин клятвы преданности (3 ур.)': GiHolyGrail,
  'паладин клятвы преданности (7 ур.)': GiHolyGrail,
  'паладин клятвы преданности (13 ур.)': GiHolyGrail,
  'паладин клятвы преданности (18 ур.)': GiHolyGrail,
  'паладин клятвы древних (3 ур.)': GiTrefoilLily,
  'паладин клятвы древних (7 ур.)': GiTrefoilLily,
  'паладин клятвы древних (13 ур.)': GiTrefoilLily,
  'паладин клятвы древних (18 ур.)': GiTrefoilLily,
  'паладин клятвы мести (3 ур.)': GiSwordWound,
  'паладин клятвы мести (7 ур.)': GiSwordWound,
  'паладин клятвы мести (13 ур.)': GiSwordWound,
  'паладин клятвы мести (18 ур.)': GiSwordWound,

  // — Классы как противники: Следопыт —
  'следопыт-охотник (3 ур.)': GiArcheryTarget,
  'следопыт-охотник (7 ур.)': GiArcheryTarget,
  'следопыт-охотник (13 ур.)': GiArcheryTarget,
  'следопыт-охотник (18 ур.)': GiArcheryTarget,
  'следопыт — повелитель зверей (3 ур.)': GiPawHeart,
  'следопыт — повелитель зверей (7 ур.)': GiPawHeart,
  'следопыт — повелитель зверей (13 ур.)': GiPawHeart,
  'следопыт — повелитель зверей (18 ур.)': GiPawHeart,

  // — Классы как противники: Плут —
  'плут-вор (3 ур.)': GiTreasureMap,
  'плут-вор (7 ур.)': GiTreasureMap,
  'плут-вор (13 ур.)': GiTreasureMap,
  'плут-вор (18 ур.)': GiTreasureMap,
  'плут-убийца (3 ур.)': GiBackstab,
  'плут-убийца (7 ур.)': GiBackstab,
  'плут-убийца (13 ур.)': GiBackstab,
  'плут-убийца (18 ур.)': GiBackstab,
  'плут — мистический ловкач (3 ур.)': GiMagicPalm,
  'плут — мистический ловкач (7 ур.)': GiMagicPalm,
  'плут — мистический ловкач (13 ур.)': GiMagicPalm,
  'плут — мистический ловкач (18 ур.)': GiMagicPalm,

  // — Классы как противники: Чародей —
  'чародей драконьей крови (3 ур.)': GiDragonBalls,
  'чародей драконьей крови (7 ур.)': GiDragonBalls,
  'чародей драконьей крови (13 ур.)': GiDragonBalls,
  'чародей драконьей крови (18 ур.)': GiDragonBalls,
  'чародей дикой магии (3 ур.)': GiSpiralBloom,
  'чародей дикой магии (7 ур.)': GiSpiralBloom,
  'чародей дикой магии (13 ур.)': GiSpiralBloom,
  'чародей дикой магии (18 ур.)': GiSpiralBloom,

  // — Классы как противники: Колдун —
  'колдун архифеи (3 ур.)': GiFairy,
  'колдун архифеи (7 ур.)': GiFairy,
  'колдун архифеи (13 ур.)': GiFairy,
  'колдун архифеи (18 ур.)': GiFairy,
  'колдун исчадия (3 ур.)': GiBatWing,
  'колдун исчадия (7 ур.)': GiBatWing,
  'колдун исчадия (13 ур.)': GiBatWing,
  'колдун исчадия (18 ур.)': GiBatWing,
  'колдун великого древнего (3 ур.)': GiSquidHead,
  'колдун великого древнего (7 ур.)': GiSquidHead,
  'колдун великого древнего (13 ур.)': GiSquidHead,
  'колдун великого древнего (18 ур.)': GiSquidHead,

  // — Классы как противники: Волшебник —
  'волшебник школы воплощения (3 ур.)': GiFireball,
  'волшебник школы воплощения (7 ур.)': GiFireball,
  'волшебник школы воплощения (13 ур.)': GiFireball,
  'волшебник школы воплощения (18 ур.)': GiFireball,
  'волшебник школы ограждения (3 ур.)': GiMagicShield,
  'волшебник школы ограждения (7 ур.)': GiMagicShield,
  'волшебник школы ограждения (13 ур.)': GiMagicShield,
  'волшебник школы ограждения (18 ур.)': GiMagicShield,
  'волшебник школы некромантии (3 ур.)': GiSkullStaff,
  'волшебник школы некромантии (7 ур.)': GiSkullStaff,
  'волшебник школы некромантии (13 ур.)': GiSkullStaff,
  'волшебник школы некромантии (18 ур.)': GiSkullStaff,
  'волшебник школы вызова (3 ур.)': GiMagicGate,
  'волшебник школы вызова (7 ур.)': GiMagicGate,
  'волшебник школы вызова (13 ур.)': GiMagicGate,
  'волшебник школы вызова (18 ур.)': GiMagicGate,

  // — Высокоуровневые боссы (ПО 10–30) —
  'древний белый дракон': GiIceberg,
  'древний синий дракон': GiDoubleDragon,
  'древний зелёный дракон': GiDragonOrb,
  'древний чёрный дракон': GiDragonSpiral,
  'древний золотой дракон': GiSpikedDragonHead,
  'древний серебряный дракон': GiSeaDragon,
  'молодой золотой дракон': GiDragonHead,
  'дьявол ямы': GiFireSilhouette,
  'кракен': GiOctopus,
  'солар': GiSunPriest,
  'марилит': GiSeaSerpent,
  'нага-страж': GiCobra,
  'слаад смерти': GiFrogPrince,
  'рок': GiEagleEmblem,
  'гинософинкс': GiAngelWings,
  'ифрит': GiSalamander,
  'джинн': GiDjinn,
  'ракшас': GiTigerHead,
  'ледяной дьявол': GiFrostfire,
  'мумия-владыка': GiMummyHead,
  'древний бронзовый дракон': GiSeaDragon,
  'древний медный дракон': GiDragonShield,
  'древний латунный дракон': GiDragonBreath,
  'взрослый золотой дракон': GiSpikedDragonHead,
  'взрослый медный дракон': GiDragonOrb,
  'взрослый латунный дракон': GiDoubleDragon,
  'андросфинкс': GiLion,
  'дракон-черепаха': GiSeaTurtle,
  'рыцарь смерти': GiCrestedHelmet,
  'они': GiOgre,
  'маг дроу': GiWizardFace,
  'взрослый серебряный дракон': GiDragonSpiral,
  'взрослый бронзовый дракон': GiDragonBreath,
  'молодой синий дракон': GiDoubleDragon,
  'молодой серебряный дракон': GiDragonShield,
  'молодой зелёный дракон': GiDragonOrb,
  'молодой бронзовый дракон': GiSeaDragon,
  'жрица дроу': GiHolySymbol,
  'слаад серый': GiFrogPrince,
  'морозный великан': GiIceberg,
  'циклоп': GiCyclops
}

const RACE_EMBLEM: Record<string, IconType> = {
  human: GiVisoredHelm,
  elf: GiElfHelmet,
  'half-elf': GiElfEar,
  drow: GiSpiderAlt,
  eladrin: GiPointyHat,
  dwarf: GiDwarfFace,
  duergar: GiMiningHelmet,
  gnome: GiGears,
  halfling: GiSlingshot,
  dragonborn: GiDragonHead,
  kobold: GiImp,
  lizardfolk: GiLizardman,
  'yuan-ti': GiSnakeTongue,
  tiefling: GiDevilMask,
  aasimar: GiAngelWings,
  goliath: GiGiant,
  tabaxi: GiCat,
  firbolg: GiOakLeaf,
  genasi: GiFlame,
  kenku: GiRaven,
  aarakocra: GiSeagull,
  triton: GiTrident,
  tortle: GiTurtle,
  warforged: GiRobotGolem,
  shifter: GiWolfHead,
  changeling: GiDominoMask,
  doppelganger: GiCardJoker,
  satyr: GiGoat,
  centaur: GiCentaur,
  fairy: GiFairy,
  goblin: GiGoblinHead,
  hobgoblin: GiSpartanHelmet,
  bugbear: GiBearFace,
  orc: GiOrcHead,
  gnoll: GiClaws,
  'half-orc': GiOrcHead,
  githyanki: GiAlienStare,
  githzerai: GiMeditation,
  sahuagin: GiSharkJaws,
  'kuo-toa': GiFishMonster,
  'mind-flayer': GiBrainTentacle
}

export function emblemForType(ruType: string): IconType {
  return TYPE_EMBLEM[ruType.trim().toLowerCase()] ?? GiCheckedShield
}
export function emblemForRace(raceId: string): IconType {
  // PH24 builds use suffixed ids (`aasimar-ph24`, `elf-ph24`, …). Strip the
  // suffix so the existing emblem map matches both lore-style ids in Races
  // and progression-style ids in Игрок.
  const key = raceId.replace(/-ph24$/, '')
  return RACE_EMBLEM[key] ?? GiCheckedShield
}

const CLASS_EMBLEM: Record<string, IconType> = {
  'barbarian-ph24': GiBattleAxe,
  'bard-ph24': GiLyre,
  'cleric-ph24': GiHolySymbol,
  'druid-ph24': GiOakLeaf,
  'fighter-ph24': GiSwordsEmblem,
  'monk-ph24': GiMonkFace,
  'paladin-ph24': GiCrossShield,
  'ranger-ph24': GiBowArrow,
  'rogue-ph24': GiHoodedAssassin,
  'sorcerer-ph24': GiMagicPalm,
  'warlock-ph24': GiEyeOfHorus,
  'wizard-ph24': GiWizardFace
}

export function emblemForClass(classId: string): IconType {
  return CLASS_EMBLEM[classId] ?? GiCheckedShield
}

/** Per-name override, falling back to the monster's type emblem. */
export function emblemForMonster(m: { name: string; type: string }): IconType {
  return NAME_EMBLEM[m.name.trim().toLowerCase()] ?? emblemForType(m.type)
}

interface Props {
  emblem: IconType
  src?: string
  size?: number
  className?: string
}

/** Gilded medallion portrait: custom image if provided, else a heraldic emblem. */
export default function Portrait({ emblem: Icon, src, size = 48, className = '' }: Props): JSX.Element {
  return (
    <div
      className={`relative flex shrink-0 items-center justify-center overflow-hidden rounded-full ${className}`}
      style={{
        width: size,
        height: size,
        background: 'radial-gradient(circle at 38% 30%, #efe5cf, #d8c39a)',
        boxShadow: 'inset 0 0 0 2px rgba(184,137,59,0.9), inset 0 0 8px rgba(90,60,20,0.5), 0 1px 3px rgba(0,0,0,0.5)'
      }}
    >
      {src ? (
        <img src={src} alt="" className="h-full w-full object-cover" />
      ) : (
        <Icon size={size * 0.62} color="#5a2a1a" />
      )}
    </div>
  )
}
